export type StylesState = {
  styles: Style[]
}

export const stylesState: StylesState = {
  styles: [
    {
      type: 'TOC',
      enabled: false,
      name: 'Table of Contents',
      fontSize: '18pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.3',
      marginTop: '18pt',
      marginBottom: '6pt'
    },
    {
      type: 'TOC_H1',
      enabled: false,
      name: 'TOC Heading Level 1',
      fontSize: '18pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.3',
      marginTop: '16pt',
      marginBottom: '6pt'
    },
    {
      type: 'TOC_H2',
      enabled: false,
      name: 'TOC Heading Level 2',
      fontSize: '16pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.3',
      marginTop: '14pt',
      marginBottom: '6pt'
    },
    {
      type: 'TOC_H3',
      enabled: false,
      name: 'TOC Heading Level 3',
      fontSize: '14pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.3',
      marginTop: '12pt',
      marginBottom: '6pt'
    },
    {
      type: 'TOC_H4',
      enabled: false,
      name: 'TOC Heading Level 4',
      fontSize: '12pt',
      fontWeight: 'italic',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '10pt',
      marginBottom: '4pt'
    },
    {
      type: 'TOC_H5',
      enabled: false,
      name: 'TOC Heading Level 5',
      fontSize: '12pt',
      fontWeight: 'italic',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '10pt',
      marginBottom: '4pt'
    },
    {
      type: 'H1',
      enabled: true,
      name: 'Title',
      fontSize: '18pt',
      fontWeight: 'bold',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.5',
      marginTop: '24pt',
      marginBottom: '12pt'
    },
    {
      type: 'H2',
      enabled: true,
      name: 'Heading 1',
      fontSize: '18pt',
      fontWeight: 'bold',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.4',
      marginTop: '20pt',
      marginBottom: '12pt'
    },
    {
      type: 'H3',
      enabled: true,
      name: 'Heading 2',
      fontSize: '16pt',
      fontWeight: 'bold',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.4',
      marginTop: '18pt',
      marginBottom: '10pt'
    },
    {
      type: 'H4',
      enabled: true,
      name: 'Heading 3',
      fontSize: '14pt',
      fontWeight: 'bold',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.3',
      marginTop: '16pt',
      marginBottom: '8pt'
    },
    {
      type: 'H5',
      enabled: true,
      name: 'Heading 4',
      fontSize: '12pt',
      fontWeight: 'bold',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.3',
      marginTop: '14pt',
      marginBottom: '6pt'
    },
    {
      type: 'H6',
      enabled: true,
      name: 'Heading 5',
      fontSize: '10pt',
      fontWeight: 'bold',
      color: '#000',
      fontFamily: 'Times New Roman',
      align: 'left',
      marginBottom: '0px',
      marginTop: '0px',
      lineHeight: '1'
    },
    {
      type: 'P',
      enabled: true,
      name: 'Body',
      fontSize: '12pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '12pt',
      marginBottom: '6pt'
    },
    {
      type: 'APP_LEM',
      enabled: false,
      name: 'Apparatus Lemma',
      fontSize: '12pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '12pt',
      marginBottom: '6pt'
    },
    {
      type: 'APP_VAR',
      enabled: false,
      name: 'Apparatus Entry',
      fontSize: '12pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '12pt',
      marginBottom: '6pt'
    },
    {
      type: 'ANN',
      enabled: false,
      name: 'Annotation',
      fontSize: '12pt',
      fontWeight: 'regular',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '12pt',
      marginBottom: '6pt'
    },
    {
      type: 'NOTE_REF_TXT',
      enabled: false,
      name: 'Reference to a Note in the text',
      fontSize: '12pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '12pt',
      marginBottom: '6pt'
    },
    {
      type: 'NOTE_REF_FOOT',
      enabled: false,
      name: 'Reference to a Note in footnote',
      fontSize: '10pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '10pt',
      marginBottom: '5pt'
    },
    {
      type: 'NOTE',
      enabled: false,
      name: 'Notes',
      fontSize: '10pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '10pt',
      marginBottom: '5pt'
    },
    {
      type: 'BIB',
      enabled: false,
      name: 'Bibliographic Reference',
      fontSize: '12pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '12pt',
      marginBottom: '6pt'
    },
    {
      type: 'HEAD',
      enabled: false,
      name: 'Header',
      fontSize: '12pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '10pt',
      marginBottom: '5pt'
    },
    {
      type: 'FOOT',
      enabled: false,
      name: 'Footer',
      fontSize: '12pt',
      fontWeight: 'normal',
      fontFamily: 'Times New Roman',
      color: '#000000',
      align: 'left',
      lineHeight: '1.2',
      marginTop: '10pt',
      marginBottom: '5pt'
    }
  ]
}
