export type StylesState = {
    styles: Style[];
}

export const stylesState: StylesState = {
    styles: [
        {
            id: "1",
            type: "TOC",
            level: 1,
            enabled: true,
            name: "Table of Contents",
            fontSize: "18pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: "left",
            lineHeight: "1.3",
            marginTop: undefined,
            marginBottom: undefined,
        },
        {
            id: "2",
            type: "TOC_H1",
            level: 2,
            enabled: true,
            name: "TOC Heading Level 1",
            fontSize: "18pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: "1.3",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "3",
            type: "TOC_H2",
            level: 3,
            enabled: true,
            name: "TOC Heading Level 2",
            fontSize: "16pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: "1.3",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "4",
            type: "TOC_H3",
            level: 4,
            enabled: true,
            name: "TOC Heading Level 3",
            fontSize: "14pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: "1.3",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "5",
            type: "TOC_H4",
            level: 5,
            enabled: true,
            name: "TOC Heading Level 4",
            fontSize: "12pt",
            fontWeight: "italic",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: "1.2",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "6",
            type: "TOC_H5",
            level: 6,
            enabled: true,
            name: "TOC Heading Level 5",
            fontSize: "12pt",
            fontWeight: "italic",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: "1.2",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "7",
            type: "H1",
            level: 1,
            enabled: true,
            name: "Title",
            fontSize: "18pt",
            fontWeight: "bold",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: "left",
            lineHeight: "1",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "8",
            type: "H2",
            level: 2,
            enabled: true,
            name: "Heading 1",
            fontSize: "16pt",
            fontWeight: "bold",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: "left",
            lineHeight: "1",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "9",
            type: "H3",
            level: 3,
            enabled: true,
            name: "Heading 2",
            fontSize: "16pt",
            fontWeight: "bold",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: "left",
            lineHeight: "1",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "10",
            type: "H4",
            level: 4,
            enabled: true,
            name: "Heading 3",
            fontSize: "14pt",
            fontWeight: "bold",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: "left",
            lineHeight: "1",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "11",
            type: "H5",
            level: 5,
            enabled: true,
            name: "Heading 4",
            fontSize: "12pt",
            fontWeight: "italic",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: "left",
            lineHeight: "1",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "12",
            type: "H6",
            level: 6,
            enabled: true,
            name: "Heading 5",
            fontSize: "10pt",
            fontWeight: "italic",
            color: "#000000",
            fontFamily: "Times New Roman",
            align: "left",
            lineHeight: "1",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "13",
            type: "P",
            level: 0,
            enabled: true,
            name: "Body",
            fontSize: "12pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: "left",
            lineHeight: "1.2",
            marginTop: "12pt",
            marginBottom: "6pt"
        },
        {
            id: "14",
            type: "APP_LEM",
            level: undefined,
            enabled: true,
            name: "Apparatus Lemma",
            fontSize: "12pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: undefined,
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "15",
            type: "APP_VAR",
            level: undefined,
            enabled: true,
            name: "Apparatus Entry",
            fontSize: "12pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: undefined,
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "16",
            type: "ANN",
            level: undefined,
            enabled: true,
            name: "Annotation",
            fontSize: "12pt",
            fontWeight: "regular",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: undefined,
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "17",
            type: "NOTE_REF_TXT",
            level: undefined,
            enabled: true,
            name: "Reference to a Note in the text",
            fontSize: "12pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: undefined,
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "18",
            type: "NOTE_REF_FOOT",
            level: undefined,
            enabled: true,
            name: "Reference to a Note in footnote",
            fontSize: "10pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: undefined,
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "19",
            type: "NOTE",
            level: undefined,
            enabled: true,
            name: "Notes",
            fontSize: "10pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: undefined,
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "20",
            type: "BIB",
            level: undefined,
            enabled: true,
            name: "Bibliographic Reference",
            fontSize: "12pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: "1.2",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "21",
            type: "HEAD",
            level: undefined,
            enabled: true,
            name: "Header",
            fontSize: "12pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: "1.2",
            marginTop: undefined,
            marginBottom: undefined
        },
        {
            id: "22",
            type: "FOOT",
            level: undefined,
            enabled: true,
            name: "Footer",
            fontSize: "12pt",
            fontWeight: "normal",
            fontFamily: "Times New Roman",
            color: "#000000",
            align: undefined,
            lineHeight: undefined,
            marginTop: undefined,
            marginBottom: undefined
        }
    ]
};