export type AuthFlow = "SIGNUP" | "SIGNIN"

export type AuthRoute =
  | "SIGNUP"
  | "SIGNIN"
  | "ACCOUNT_VERIFICATION"
  | "ACCOUNT_VERIFICATION_SUCCESS"
  | "FORGOT_PASSWORD"
  | "FORGOT_PASSWORD_VERIFY_CODE"
  | "FORGOT_PASSWORD_CHANGE_PASSWORD"
  | "FORGOT_PASSWORD_CHANGE_PASSWORD_SUCCESS";
