export default {
    "sourceType": "book" as BIB_REFERENCE_TYPES,
    "title": "",
    "editor": "",
    "author": [],
    "bookTitle": "",
    "series": "",
    "seriesNumber": "",
    "volume": "",
    "numberOfVolumes": "",
    "issue": "",
    "doi": "",
    "place": "",
    "publisher": "",
    "date": "",
    "pages": "",
    "shortTitle": "",
    "url": "",
    "accessed": "",
}